name: OpenAPI Publisher

on:
  workflow_run:
    workflows: ['OpenAPI Validator']
    branches: [main]
    types:
      - completed

jobs:
  if: ${{ github.event.workflow_run.conclusion == 'success' }}
  publish-main:
    uses: ./.github/workflows/publish-openapi.yaml
    with:
      README_RESOURCE_API_ID: ${{ secrets.README_OP_API_ID }}
      README_AUTH_API_ID: ${{ secrets.README_AUTH_API_ID }}
    secrets:
      README_API_KEY: ${{ secrets.README_API_KEY }}
